# Problem Set #2

####Part 1

###Problem 1


In [52]:
L = [1,2,3,4,5,6,7,8,9,10]

In [53]:
print(max(L),min(L),sum(L)/len(L))

10 1 5.5


###Problem 2

Int ##Immutable

In [54]:
my_num = 911

In [55]:
print(my_num)

911


In [56]:
your_num = my_num

In [57]:
print(your_num)

911


In [58]:
your_num= 119
print(your_num)

119


In [59]:
my_num==your_num

False

str ##Immutable

In [60]:
my_str= str('boiled eggs')

In [61]:
print(my_str)

boiled eggs


In [62]:
your_str = my_str

In [63]:
your_str = ('Fried eggs')

In [64]:
my_str==your_str

False

list ##Mutable

In [65]:
my_list =list('jaewoolee')

In [66]:
print(my_list)

['j', 'a', 'e', 'w', 'o', 'o', 'l', 'e', 'e']


In [67]:
your_list =my_list
print(your_list)

['j', 'a', 'e', 'w', 'o', 'o', 'l', 'e', 'e']


In [68]:
your_list[0] = 'b'
print(my_list)

['b', 'a', 'e', 'w', 'o', 'o', 'l', 'e', 'e']


In [69]:
my_list==your_list

True

tuple ##Immutable

In [70]:
my_tuple =tuple('Operations')
print(my_tuple)

('O', 'p', 'e', 'r', 'a', 't', 'i', 'o', 'n', 's')


In [71]:
your_tuple = my_tuple
print(your_tuple)

('O', 'p', 'e', 'r', 'a', 't', 'i', 'o', 'n', 's')


In [72]:
your_tuple += (1,)
print(your_tuple)

('O', 'p', 'e', 'r', 'a', 't', 'i', 'o', 'n', 's', 1)


In [73]:
your_tuple == my_tuple

False

set ##Mutable

In [74]:
my_set ={1, 2, 3, 4, 2, 5}

In [75]:
your_set = my_set

In [76]:
your_set.add(50)

In [77]:
your_set == my_set

True

I conclude that 'set' and 'list' are mutable while 'int' and 'str' are immutable. 

###Problem 3

##calculator.py

In [78]:
def simplesum(val1, val2):
    the_sum = val1 + val2
    return the_sum

In [79]:
def produc(val1, val2):
    the_pro=val1*val2
    return the_pro

In [80]:
import math

##importing module

In [81]:
import calculator as ca
import math

In [82]:
def hypo (a,b):
    hypo=math.sqrt(ca.simplesum(ca.produc(a,a), ca.produc(b,b)))
    return(hypo)
    

In [83]:
hypo(3,4)

5.0

####Part2

In [84]:
import numpy as np
def MP(a,b):
    MP=np.dot(a,b)
    return(MP)

###Problem1

In [85]:
A=np.array([[3,-1,4],[4,5,6]])
B=np.array([[2,6,-5,3],[5,-8,9,7],[9,-3,-2,-3]])
MP(A,B)

array([[ 37,  14, -32, -10],
       [ 87, -34,  13,  29]])

###Problem2

In [137]:
A=np.array([[3,1,4],[1,5,9],[-5,3,1]])

In [139]:
TM= -1*np.dot(np.dot(A,A),A)+9*np.dot(A,A)-15*(A)
print(TM)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


###Problem 5

In [112]:
np.identity((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [143]:
A=np.array([[0,2,4],[1,3,5]])
B=np.array([[3,0,0],[3,3,0],[3,3,3]])
C=np.array([[-2,0,0],[0,-2,0],[0,0,-2]])
D=np.zeros((3,3))
D2=np.zeros((2,2))
D3=np.zeros((3,2))
D4=np.zeros((2,3))
E=np.identity(3)
F=A.T
H=np.vstack((D,A,B))
I=np.vstack((F,D2,D3))
J=np.vstack((E,D4,C))
np.column_stack((H,I,J))


array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2.,  0.,  0.],
       [ 3.,  3.,  0.,  0.,  0.,  0., -2.,  0.],
       [ 3.,  3.,  3.,  0.,  0.,  0.,  0., -2.]])

####Part3

Problem 1

In [2]:
class Backpack:
    """A Backpack object class. Has a name and color, and max_size.
    Attributes:
    name (str): the name of the backpack's owner.
    color (str): the color of the backpack
    max_size(int): the capacity of the backpack
    contents (list): the contents of the backpack. 
    """
    def __init__(self, name, color, max_size=5): # This function is the constructor.
        """Set the name, color, max_size and initialize an empty list of contents. 
        """
        self.name = name # Initialize some attributes.
        self.color = color
        self.max_size = max_size
        self.contents =[]

    def put(self,item):
        """Add 'item' to the backback's list of contents if the number of contents is less than max_size. Otherwise, print "No Room!" and do not add the item to the list of contents
        """
        if len(self.contents) < self.max_size:
            self.contents.append(item)
        else: print("No Room!")
    def take(self,item):
        """Remove 'item' from the backpack's list of contents."""
        self.contents.remove(item)
    def dump(self, item):
        """Empty 'item' from the backpack's list of contents."""



In [159]:
my_backpack= Backpack("Jaewoo", "Black")
type(my_backpack)
print(my_backpack.name, my_backpack.color, my_backpack.max_size)
my_backpack.put("iPad Pro")
my_backpack.put("Laptop")
my_backpack.put("Jacket")
my_backpack.put("Monitor")
my_backpack.put("Bicycle")
my_backpack.put("car")
my_backpack.contents

Jaewoo Black 5
No Room!


['iPad Pro', 'Laptop', 'Jacket', 'Monitor', 'Bicycle']

In [147]:
def test_backpack():
    testpack = Backpack("Jaewoo", "black")
    if testpack.name != "Jaewoo":
        print("Backpack.name assigned incorrectly")
    for item in ["pencil", "pen", "paper", "computer"]:
        testpack.put(item)
    print("Contents:", testpack.contents)
    # ...

###Problem 2

In [21]:
class Jetpack(Backpack):
    """A Jetpack object class. Inherits from the Backpack class.
    A jetpack is smaller than a backpack and need fuel.
    
    Attributes:
        name (str): the name of the knapsack's owner
        color (str): the color of the knapsack.
        max_size (int): the maximum number of items that can fit inside
        fuel (int): the amount of fuel in the jetpack
    """
    def __init__(self, name, color, max_size=2, fuel=10):
        """Use the Backpack constructor to initialize the name, color, and max_size attributes. A knapsack only holds 2 item by defualt and contain 10 units of fuel by default.
        
        Parameters:
            name (str):the name of the knapsack's owner.
            color (str): the color of the knapsack. 
            max_size (int): the maximum number of items that can fit inside.
            fuel (int): the amount of fuel in the jetpack
        """
        Backpack.__init__(self, name, color, max_size)
        self.fuel = fuel
    def fly(self,fuel):
        """Stop burning the fuel if the user tries to burn more fuel than remains, and print"Not enough fuel", and do not decrement the fuel."""
        if self.fuel < fuel:
            print("Not enough fuel")
        else:
            self.fuel = self.fuel - fuel
    def dump(self, item):
        """Empty 'item' from the jetpack's list of contents."""
    def dump(self, fuel):
        """Empty fuel from the jetpack' tank."""

##Testing class Jetpack 

In [23]:
my_jetpack= Jetpack("Jaewoo", "Black")
type(my_jetpack)
print(my_jetpack.name, my_jetpack.color, my_jetpack.max_size, my_jetpack.fuel)
my_jetpack.put("iPad Pro")
my_jetpack.put("Laptop")
my_jetpack.put("Jacket")
my_jetpack.put("Monitor")
my_jetpack.put("Bicycle")
my_jetpack.put("car")
my_jetpack.contents
my_jetpack.fly(9)
my_jetpack.fuel

Jaewoo Black 2 10
No Room!
No Room!
No Room!
No Room!


1